use_frameworks!

platform :ios, '8.0'

target 'HTSimpleVideoPlayer_Example' do
  pod 'HTSimpleVideoPlayer', :path => '../'

  target 'HTSimpleVideoPlayer_Tests' do
    inherit! :search_paths

    
  end
end
